[package]
name = "p2p-node-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.3.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.95"
tokio = { version = "1.26.0", features = ["full"] }

